### PR TITLE
Pagination and refactoring

### PR DESCRIPTION
**Pull request by pschmitt**

### CODE REVIEW

**Comment by JoaquimEsteves** [comment]
lgtm

What manner of brilliant mind programmed that `_paginatio_request` as an iterable?!

Truly a programmer of vast intellect

**Comment by pschmitt** [comment]
> lgtm

Hard to confirm w/o a working d42 instance though. But yeah, this *should* work :tm:

Will refactor a bit now.

**Comment by JoaquimEsteves** [comment]
I'd put the `int_cast` in the types.py since it's there to appease the typing gods anyway, having a whole file for it atm seems a bit much imo.

But it's a minor thing; I can live without it

**Comment by pschmitt** [comment]
> I'd put the int_cast in the types.py since it's there to appease the typing gods anyway, having a whole file for it atm seems a bit much imo.

I've actually already moved it to to `toolbox.py`.

**Comment by pschmitt** [comment]
> I'd put the int_cast in the types.py
Done. 38f8479

**Pull request merged**
